name: Coverage Comment

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:ci-safe

    - name: Coverage Report as Comment
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        delete-old-comments: true

    - name: Add Coverage Summary
      run: |
        echo "## 📊 Coverage Report" >> coverage-comment.md
        echo "" >> coverage-comment.md
        echo "| Metric | Coverage |" >> coverage-comment.md
        echo "|--------|----------|" >> coverage-comment.md
        node -e "
        const fs = require('fs');
        const coverage = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
        const total = coverage.total;
        console.log(\`| Lines | \${total.lines.pct}% (\${total.lines.covered}/\${total.lines.total}) |\`);
        console.log(\`| Functions | \${total.functions.pct}% (\${total.functions.covered}/\${total.functions.total}) |\`);
        console.log(\`| Branches | \${total.branches.pct}% (\${total.branches.covered}/\${total.branches.total}) |\`);
        console.log(\`| Statements | \${total.statements.pct}% (\${total.statements.covered}/\${total.statements.total}) |\`);
        " >> coverage-comment.md

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: coverage-comment.md